### PR TITLE
Fix:  changedMonitors.forEach (montage.js)

### LINKED ISSUE #4037: The placement of monitors on the Montage page is broken again
**Describe Your Environment**
- Version of ZoneMinder 1.37

Someone somewhere broke something...... #4032

### PR DESCRIPTION
**Pull request by IgorA100**
Iterating through the array was incorrect

Possible fixes #4037

### CODE REVIEW

File: web/skins/classic/views/js/montage.js [hunk 1]
```diff
@@ -798,7 +798,7 @@ function initPage() {
 
   setInterval(() => { //Updating GridStack resizeToContent, Scale & Ratio
     if (changedMonitors.length > 0) {
-      changedMonitors.forEach(function(item, index, object) {
+      changedMonitors.slice().reverse().forEach(function(item, index, object) {
```
Comment (connortechnology) [inline web/skins/classic/views/js/montage.js:801]: It is not clear to the casual observer why the slice and reverse are neccessary. perhaps a comment would help.
Alternatively a simple for loop instead of a forEach is actually faster and you can just clear the array at the end. Would be easier to read as well.

Comment (IgorA100) [reply web/skins/classic/views/js/montage.js:801]: At the time of execution of this code, other data may be filled into the "changedMonitors" array. Therefore, it cannot be cleaned after processing all elements. Step by step cleaning is required. This is why "for" is not used.
slice().reverse() - to iterate over a copy of the array from the end, otherwise it will not be possible to correctly remove the processed monitor from the array

Comment (connortechnology) [reply web/skins/classic/views/js/montage.js:801]: Aha!  Excellent content for a comment.

So the slice makes a copy...  which we could use for on.  Maybe we should just use a while with popping off elements until the array is empty... so that if another item gets added we will process it.

**Comment by connortechnology** [comment]
Id say leave it for now.  It's not a big deal.

File: web/skins/classic/views/js/montage.js (hunk 1 above)
Comment (IgorA100) [reply web/skins/classic/views/js/montage.js:801]: I'm not ready to say anything yet.

**Comment by IgorA100** [comment]
I made changes
Try again.

> Id say leave it for now. It's not a big deal.

:)

**Comment by connortechnology** [comment]
That's got it. Well done.
